title: Isabel lawton
description: A typography in film and TV
footer_text: Copyright 2021 Isabel lawton
header_feature_image: ../uploads/gr-stocks-q8p8yor6erg-unsplash.jpg
header_text: Typography in Film and TV
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
